# Generated by Django 4.2.2 on 2023-10-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_settings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
