# Generated by Django 4.2.2 on 2023-09-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsdata',
            name='involved_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_user',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.RemoveField(
            model_name='rolepermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermissions',
            name='role',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnalyticsData',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePermissions',
        ),
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
