# Generated by Django 4.2.2 on 2023-11-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialMedia', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemreport',
            name='provider_user',
        ),
        migrations.RemoveField(
            model_name='problemreport',
            name='service',
        ),
        migrations.RemoveField(
            model_name='ratingandcomment',
            name='client_user',
        ),
        migrations.RemoveField(
            model_name='ratingandcomment',
            name='provider_user',
        ),
        migrations.RemoveField(
            model_name='ratingandcomment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialMediaIntegration',
        ),
        migrations.RemoveField(
            model_name='tagsserviceposts',
            name='service_post',
        ),
        migrations.RemoveField(
            model_name='tagsserviceposts',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privacy_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='involved_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrivacySettings',
        ),
        migrations.DeleteModel(
            name='ProblemReport',
        ),
        migrations.DeleteModel(
            name='RatingAndComment',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceStatus',
        ),
        migrations.DeleteModel(
            name='TagsServicePosts',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
