# Generated by Django 4.2.6 on 2023-11-17 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialMedia', '0004_remove_problemreport_provider_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='involved_user',
        ),
        migrations.RemoveField(
            model_name='multimedia',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient_user',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='sender_user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
        migrations.DeleteModel(
            name='Multimedia',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
