# Generated by Django 4.2.6 on 2023-11-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0008_loginrecord_delete_privacysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name=20)),
                ('token', models.CharField(max_length=60)),
                ('status', models.IntegerField(verbose_name=3)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Users.userprofile')),
            ],
        ),
    ]
