# Generated by Django 4.2.2 on 2023-10-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_userprofile_address_alter_userprofile_email_and_more'),
        ('Services', '0004_service_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile'),
        ),
    ]
